export const mockProducts = [
    {
        id: "prod_001",
        product_name: "Minimalist Ceramic Vase",
        product_description: "Handcrafted unglazed ceramic vase perfect for dried botanicals. Adds a modern, tactile element to any space.",
        price: 3400,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Ceramics",
        rating: 4.8,
        brand: "Studio Arhoj"
    },
    {
        id: "prod_002",
        product_name: "Brutalist Concrete Planter",
        product_description: "A heavy, monolithic concrete planter that develops a beautiful patina over time.",
        price: 5200,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Home Decor",
        rating: 4.5,
        brand: "Concrete Co."
    },
    {
        id: "prod_003",
        product_name: "Abstract Line Art Print",
        product_description: "Limited edition giclée print on archival paper, featuring fluid continuous line art.",
        price: 2800,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Art Prints",
        rating: 4.9,
        brand: "Atelier Prints"
    },
    {
        id: "prod_004",
        product_name: "Architectural Desk Lamp",
        product_description: "Matte black desk lamp with adjustable joints and a focused LED beam.",
        price: 8500,
        image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Lighting",
        rating: 4.7,
        brand: "Lumen"
    },
    {
        id: "prod_005",
        product_name: "Matte Black Espresso Cups (Set of 2)",
        product_description: "Thick-walled ceramic espresso cups designed to retain heat, finished in a deep matte black glaze.",
        price: 2100,
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Ceramics",
        rating: 4.6,
        brand: "Nomad Ceramics"
    },
    {
        id: "prod_006",
        product_name: "Sculptural Lounge Chair",
        product_description: "A statement piece featuring bentwood construction and premium bouclé upholstery.",
        price: 45000,
        image: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Furniture",
        rating: 4.2,
        brand: "Maison"
    },
    {
        id: "prod_007",
        product_name: "Geometric Incense Holder",
        product_description: "Solid brass incense holder machined into an exact geometric prism.",
        price: 1800,
        image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1000&auto=format&fit=crop",
        status: "LOW_STOCK",
        category: "Home Decor",
        rating: 4.4,
        brand: "AYTM"
    },
    {
        id: "prod_008",
        product_name: "Textured Linen Throw",
        product_description: "Heavyweight stonewashed linen throw blanket in a natural ash shade.",
        price: 6400,
        image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Textiles",
        rating: 4.8,
        brand: "Cultiver"
    },
    {
        id: "prod_009",
        product_name: "Monochrome Wall Clock",
        product_description: "A silent sweep movement clock stripped of all numbers for a pure minimalist read.",
        price: 3200,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Home Decor",
        rating: 4.1,
        brand: "Menu"
    },
    {
        id: "prod_010",
        product_name: "Oak Wood Coffee Table",
        product_description: "Low-profile coffee table crafted from solid European oak with dovetail joints.",
        price: 28000,
        image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop",
        status: "OUT_OF_STOCK",
        category: "Furniture",
        rating: 4.9,
        brand: "Frama"
    },
    {
        id: "prod_011",
        product_name: "Ribbed Glass Carafe",
        product_description: "Mouth-blown ribbed glass carafe, perfect for water or wine.",
        price: 2600,
        image: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Glassware",
        rating: 4.5,
        brand: "Ferm Living"
    },
    {
        id: "prod_012",
        product_name: "Minimalist Floor Lamp",
        product_description: "A slender steel rod emitting a soft, diffuse ambient light along its entire length.",
        price: 12500,
        image: "https://images.unsplash.com/photo-1532453288672-3a27e9be2efd?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Lighting",
        rating: 4.3,
        brand: "Flos"
    },
    {
        id: "prod_013",
        product_name: "Tote Bag - Heavy Canvas",
        product_description: "Structured utilitarian tote bag made from 24oz cotton canvas.",
        price: 3500,
        image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Accessories",
        rating: 4.7,
        brand: "Aeta"
    },
    {
        id: "prod_014",
        product_name: "Hand-poured Soy Candle",
        product_description: "Notes of cedar, vetiver, and smoky sandalwood in a reusable blackened steel vessel.",
        price: 2200,
        image: "https://images.unsplash.com/photo-1528343105740-ff8ae641c888?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Home Decor",
        rating: 4.6,
        brand: "Le Labo"
    },
    {
        id: "prod_015",
        product_name: "Aluminum Stationery Tray",
        product_description: "Milled from a single block of aerospace-grade aluminum, anodized black.",
        price: 1900,
        image: "https://images.unsplash.com/photo-1501162943152-edab3d50df5b?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Office",
        rating: 4.4,
        brand: "Grovemade"
    },
    {
        id: "prod_016",
        product_name: "Wabi-Sabi Tea Bowl",
        product_description: "Asymmetrical matcha bowl featuring a crackled glaze that highlights its organic form.",
        price: 3100,
        image: "https://images.unsplash.com/photo-1524143878510-ce2b5eeb59dc?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Ceramics",
        rating: 4.8,
        brand: "Kinto"
    },
    {
        id: "prod_017",
        product_name: "Brass Bookends",
        product_description: "Solid unlacquered brass bookends that will tarnish beautifully over the years.",
        price: 4200,
        image: "https://images.unsplash.com/photo-1550583724-b2692bc1ffed?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Office",
        rating: 4.5,
        brand: "Craighill"
    },
    {
        id: "prod_018",
        product_name: "Alpaca Wool Blanket",
        product_description: "Incredibly soft, hypollergenic baby alpaca wool throw in charcoal gray.",
        price: 9800,
        image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Textiles",
        rating: 4.9,
        brand: "Tekla"
    },
    {
        id: "prod_019",
        product_name: "Terrazzo Coasters",
        product_description: "Set of 4 heavy terrazzo coasters with cork backing to protect surfaces.",
        price: 1500,
        image: "https://images.unsplash.com/photo-1511556820780-d912e42b4980?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Home Decor",
        rating: 4.2,
        brand: "Capra Designs"
    },
    {
        id: "prod_020",
        product_name: "Leather Lounge Ottoman",
        product_description: "Full-grain aniline leather ottoman, perfectly paired with our sculptured lounge chair.",
        price: 18500,
        image: "https://images.unsplash.com/photo-1507133750073-7b47a0631f4a?q=80&w=1000&auto=format&fit=crop",
        status: "LOW_STOCK",
        category: "Furniture",
        rating: 4.7,
        brand: "Maison"
    },
    {
        id: "prod_021",
        product_name: "Steel Wire Basket",
        product_description: "Geometric powder-coated steel basket for magazine storage or firewood.",
        price: 4800,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Home Decor",
        rating: 4.6,
        brand: "Ferm Living"
    },
    {
        id: "prod_022",
        product_name: "Abstract Canvas Painting",
        product_description: "Original acrylic on canvas with heavy impasto textures in neutral tones.",
        price: 35000,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Art Prints",
        rating: 5.0,
        brand: "Studio M"
    },
    {
        id: "prod_023",
        product_name: "Japanese Chef Knife",
        product_description: "High-carbon steel Gyuto knife with an octagonal walnut handle.",
        price: 16000,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Kitchen",
        rating: 4.9,
        brand: "Kin"
    },
    {
        id: "prod_024",
        product_name: "Pendant Light - Concrete",
        product_description: "Cast concrete pendant light focusing illumination directly downwards over dining areas.",
        price: 7200,
        image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Lighting",
        rating: 4.4,
        brand: "Muuto"
    },
    {
        id: "prod_025",
        product_name: "Linen Apron",
        product_description: "Cross-back linen apron with deep reinforced pockets for kitchen or studio work.",
        price: 3800,
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Apparel",
        rating: 4.7,
        brand: "Fog Linen"
    },
    {
        id: "prod_026",
        product_name: "Walnut Serving Board",
        product_description: "Live-edge solid black walnut serving board finished with food-safe mineral oil.",
        price: 5400,
        image: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Kitchen",
        rating: 4.8,
        brand: "WoodWorks"
    },
    {
        id: "prod_027",
        product_name: "Sleek Stainless Steel Flask",
        product_description: "Vacuum-insulated minimalist flask keeping liquids hot or cold for 24 hours.",
        price: 2900,
        image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Accessories",
        rating: 4.5,
        brand: "Snow Peak"
    },
    {
        id: "prod_028",
        product_name: "Fluted Glass Tumbler",
        product_description: "Elegant set of 4 fluted glass tumblers, dishwasher safe.",
        price: 2400,
        image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Glassware",
        rating: 4.6,
        brand: "Ferm Living"
    },
    {
        id: "prod_029",
        product_name: "Round Wall Mirror",
        product_description: "Frameless round mirror with a subtle smoked glass tint.",
        price: 11000,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Home Decor",
        rating: 4.3,
        brand: "Audo"
    },
    {
        id: "prod_030",
        product_name: "Woven Paper Storage Basket",
        product_description: "Durable and flexible storage basket made intensely compressed recycled paper.",
        price: 2600,
        image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Home Decor",
        rating: 4.1,
        brand: "Uashmama"
    },
    {
        id: "prod_031",
        product_name: "Onyx Statement Ring",
        product_description: "A stark black onyx stone set in brushed matte sterling silver.",
        price: 14500,
        image: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Accessories",
        rating: 4.8,
        brand: "Tom Wood"
    },
    {
        id: "prod_032",
        product_name: "Silk Sleep Mask",
        product_description: "Pure mulberry silk sleep mask filled with natural lavendar.",
        price: 2200,
        image: "https://images.unsplash.com/photo-1532453288672-3a27e9be2efd?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Apparel",
        rating: 4.7,
        brand: "Slip"
    },
    {
        id: "prod_033",
        product_name: "Minimal Table Clock",
        product_description: "A brutalist slab of untreated brass forming a simple desk block watch featuring Dieter Rams inspired hands.",
        price: 6800,
        image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000&auto=format&fit=crop",
        status: "IN_STOCK",
        category: "Office",
        rating: 4.5,
        brand: "Braun"
    },
    {
        id: "prod_034",
        product_name: "Suede Room Slippers",
        product_description: "Unstructured soft goat suede indoor slippers lined with shearling.",
        price: 4900,
        image: "https://images.unsplash.com/photo-1528343105740-ff8ae641c888?q=80&w=1000&auto=format&fit=crop",
        status: "LOW_STOCK",
        category: "Apparel",
        rating: 4.6,
        brand: "Mulo"
    }
];
